version: '2.1'
services:
  mysqlget5:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=<NOT_SO_SECRET_PW>
    mem_limit: 512m
    restart: always
    ports:
    - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  get5:
    image: alget5:latest
    ports:
    - "8888:8080"
    restart: always
    volumes:
    - ./prod_config.py:/app/instance/prod_config.py
    environment:
    - MYSQL_HOST=mysqlget5
    - DB_DATABASE=get5
    - DB_USERNAME=<user!!!>
    - DB_PASSWORD=<pw!!!>
    - MYSQL_ROOT_PASSWORD=<NOT_SO_SECRET_PW>
    links:
    - mysqlget5:mysqlget5
    mem_limit: 512m
    depends_on:
      mysqlget5:
        condition: service_healthy
